[project]
name = "soma-env-0.0"
channels = ["pytorch", "nvidia", "conda-forge", "https://brainvisa.info/neuro-forge"]
platforms = ["linux-64"]
version = "0.0"

[dependencies]
python = ">=3.10,>=3.9,==3.11"
fire = "*"
conda-build = "*"
pyyaml = "*"
dateutils = "*"
cmake = "*"
gcc = "*"
git = "*"
gitpython = "*"
gxx = "*"
libglu = "*"
libglvnd-devel-cos7-x86_64 = "*"
libstdcxx-devel_linux-64 = "*"
make = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesalib-devel-only = "*"
pip = "*"
pyaml = "*"
pytest = "*"
rattler-build = ">=0.13"
six = "*"
sphinx = "*"
toml = "*"
virtualgl = "*"
"sigcpp-2.0" = "*"
libblitz = "*"
boost-cpp = "*"
gfortran = "*"
dcmtk = "*"
numpy = "<2"
libminc = "*"
openjpeg = "*"
pywebp = "*"
objgraph = "*"
graphviz = "*"
doxygen = "*"
pkgconfig = "*"
nipype = "*"
xlrd = "*"
xlwt = "*"
openpyxl = "*"
lark-parser = ">0.7.0"
python-dateutil = "*"
requests = "*"
cryptography = "*"
pytorch = "*"
torchvision = "*"
scikit-learn = "*"
pcl = "*"
configobj = "*"
pyqtwebkit = "*"
scipy = "*"
traits = "<7"
spm12 = "*"
reportlab = "*"
libsvm = "*"
qwt = "*"
matplotlib = "*"
qtconsole = "*"
ipycanvas = "*"
ipywidgets = "*"
ipyevents = "*"
notebook = "*"
pygltflib = "*"
nodejs = "*"
xvfb = "*"
mesalib_software = "*"
pydantic = "<2"
pyqt = "*"
pyqtwebengine = "*"
ipykernel = "*"
pycryptodome = "*"
pandas = "*"
libgl = "*"
libopengl = "*"
pydicom = "*"
pre-commit = ">=4.1.0,<5"

[dependencies.libjpeg-turbo]
channel = "conda-forge"
version = ">=3.0.0"

[activation]
scripts = ["activate.sh"]
